### ISSUE TITLE
What is the patient_id for custom dataset?

### ISSUE THREAD

**Issue by HelloWorldLTY** [yuzhenmao/ScRAT#2]
Hi, thanks for your great work. I intend to run your method with custom datasets, however, I used the sample id as patient id but faced an error:

```
Traceback (most recent call last):
  File "/gpfs/scratchfs01/site/u/liut61/ScRAT/main.py", line 289, in <module>
    for train_index, test_index in rkf.split(num):
  File "/home/liut61/miniforge3/envs/cellm/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 1598, in split
    for train_index, test_index in cv.split(X, y, groups):
  File "/home/liut61/miniforge3/envs/cellm/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 409, in split
    raise ValueError(
ValueError: Cannot have number of splits n_splits=2 greater than the number of samples: n_samples=0.
```

May I know the format of patient id I should use? Is it same as the obs_names of each cell? Thanks.

**Comment by yuzhenmao** [comment]
Thank you for your interest in our work. The patient id serves as an indicator of which patient a particular cell belongs to. For example, in the Haniffa dataset we provide, the format of the patient ID is:

![Screenshot 2024-07-14 at 6 42 47 PM](https://github.com/user-attachments/assets/23bb09b9-2e9a-4379-88d8-033fc48b1615)

**Comment by HelloWorldLTY** [comment]
Thanks. I used the same category setting method but I still faced this error. Would you please upload a sample custom dataset? Thanks a lot!

**Comment by yuzhenmao** [comment]
No problem. Please check this: https://github.com/yuzhenmao/ScRAT?tab=readme-ov-file#for-dataset-mentioned-in-our-paper

**Comment by HelloWorldLTY** [comment]
Thanks, but if my understanding is correct, all of the files you mentioned are pkl files not h5ad files. Is it proper if I transfer those pkl files into a h5ad file to test your model? Thanks.

**Comment by yuzhenmao** [comment]
The issue might be due to this line of code: https://github.com/yuzhenmao/ScRAT/blob/main/dataloader.py#L209 or https://github.com/yuzhenmao/ScRAT/blob/main/dataloader.py#L216. If the number of cells for a patient is less than 500, the original code will discard it. This causes your p_idx in https://github.com/yuzhenmao/ScRAT/blob/main/main.py#L283 to be empty.

**Comment by HelloWorldLTY** [comment]
Ok, thanks a lot.
